### ISSUE TITLE
getByRole does not work in some cases

### ISSUE THREAD

**Issue by roman-gula** [capricorn86/happy-dom#1122]
**Describe the bug**
Hi! I use Vite with MUI and noticed that with `happy-dom` my test fails. With `jsdom` it works. 
I can't find what is the problem. Please see code below

**To Reproduce**
```js
it('with Accordion', () => {
  render(
    <Accordion>
      <AccordionSummary>aaa</AccordionSummary>
    </Accordion>
  );

  expect(screen.getByRole('button')).toBeInTheDocument();
});
```

[Example on Stackblitz](https://stackblitz.com/edit/github-5r4uqn-ur1emn?file=src%2FApp.test.jsx)

**Comment by DavidRNogueira** [comment]
I also have this issue when using different component libraries. The issue seems to be that HappyDOM may not be looking at the `role` attribute, but rather its only looking at the actual element type? The component library is also using a div with `role="button"` and HappyDOM does not pick it up properly.
