### ISSUE TITLE
DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by marcotas** [capricorn86/happy-dom#1429]
**Describe the bug**
I'm getting this error inside radix-vue after updating the happy-dom package from `14.7.1` to `14.10.1`. It seems to me that it's a change on the most recent version of happy-dom package that is breaking my unit tests.

Everything works as expected on the browser. How should I solve this? Any ideas?

**Screenshots**
<img width="1700" alt="image" src="https://github.com/capricorn86/happy-dom/assets/3236791/b68086d5-146d-4fa3-8697-b4e452c2b2c8">

Error text:
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
 ❯ Function.insertBefore node_modules/.pnpm/happy-dom@14.8.3/node_modules/happy-dom/src/nodes/node/NodeUtility.ts:181:10
 ❯ Function.insertBefore node_modules/.pnpm/happy-dom@14.8.3/node_modules/happy-dom/src/nodes/element/ElementUtility.ts:215:16
 ❯ HTMLElement.[insertBefore] node_modules/.pnpm/happy-dom@14.8.3/node_modules/happy-dom/src/nodes/element/Element.ts:522:25
 ❯ HTMLElement.insertBefore node_modules/.pnpm/happy-dom@14.8.3/node_modules/happy-dom/src/nodes/node/Node.ts:367:43
 ❯ HTMLElement.insertAdjacentElement node_modules/.pnpm/happy-dom@14.8.3/node_modules/happy-dom/src/nodes/element/Element.ts:601:9
 ❯ node_modules/.pnpm/radix-vue@1.7.4_vue@3.4.27_typescript@5.4.5_/node_modules/radix-vue/dist/index.js:897:19
    895|       return;
    896|     const t = document.querySelectorAll("[data-radix-focus-guard]");
    897|     document.body.insertAdjacentElement(
       |                   ^
    898|       "afterbegin",
    899|       t[0] ?? Po()
 ❯ callWithErrorHandling node_modules/.pnpm/@vue+runtime-core@3.4.27/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19
 ❯ callWithAsyncErrorHandling node_modules/.pnpm/@vue+runtime-core@3.4.27/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:202:17
 ❯ ReactiveEffect.getter [as fn] node_modules/.pnpm/@vue+runtime-core@3.4.27/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1900:16
 ❯ ReactiveEffect.run node_modules/.pnpm/@vue+reactivity@3.4.27/node_modules/@vue/reactivity/dist/reactivity.cjs.js:181:19
```

**Device:**
 - OS: macOS Sonoma 14.4.1

**Comment by btea** [comment]
Can you provide a reproduction link?

**Comment by juandiegombr** [comment]
It happens also to me using the Dialog component from Radix. It seems that happens because the focus guards functionality.

<img width="869" alt="image" src="https://github.com/capricorn86/happy-dom/assets/34795714/9ffd5985-e839-42b3-8336-45ae502cfbe4">


After some digging I have realized that it performs some radix utilities trigger `document.body.insertAdjacentElement('afterbegin', element); `:

- It generates that the `insertBefore` is called with a node that the parent already contains.
- So the newNode and the referenceNode in the `Node.insertBefore` method are the same element.
- This [fix](https://github.com/capricorn86/happy-dom/pull/1407) removes the newNode that is also the referenceNode from the parent node.
- And it generates the error because the reference node it was deleted from the parent.
