### ISSUE TITLE
Support for insertAdjecentText

### ISSUE THREAD

**Issue by kr8n3r** [capricorn86/happy-dom#221]
Hi, 
looking to replace jsdom so I'm looking to add either just the `insertAdjecentText` method or the entire [insert-adjecent](https://dom.spec.whatwg.org/#insert-adjacent) suite of methods, depending on projects philosophy.

Looking at the code structure I wasn't quite sure how to split the methods. 
Guidance would be appreciated so I can put together a PR.

Thanks.

**Comment by capricorn86** [comment]
Hi @kr8n3r!

Nice to hear that you would like to contribute :slightly_smiling_face: 

Both separating the features as smaller PR:s or doing everything in a bigger one works fine by me.

There is a guide for how to install, compile, test and what formats commits should have etc. here:
https://github.com/capricorn86/happy-dom/blob/master/docs/contributing.md

Happy DOM uses interfaces to ensure that the specs are followed. The interfaces are also used to prevent circular dependencies etc. that can occur due to the nature of how the DOM works.

All three methods seem to be part of the Element interface.

I would do the following:

1. Add the methods according to the specs to the IElement interface located at packages/happy-dom/src/nodes/element/IElement.ts. Whenever a Node or Element is used as an attribute or return type, use its interface as type and not the class implementing the interface.
2. Implement the methods in Element.ts that is located in the same directory as IElement. Same here, use interfaces for attributes and return types when it is a Node or Element. Both childNodes and children need to be updated if you add or remove nodes. You also have to update the parent node if nodes are moved. Therefore it is probably best to re-use methods like insertBefore() or appendChild() as they already have this logic.
3. Create unit tests for the implemented methods in packages/happy-dom/test/nodes/element/Element.test.ts

Let me know if something is still unclear or if you have any more questions! :slightly_smiling_face:

**Comment by capricorn86** [comment]
@kr8n3r if you need to parse HTML you can look at ChildNodeUtility.after() as an example where it is using DOMParser.

**Comment by capricorn86** [comment]
@kr8n3r do you still want to make a contribution? Otherwise I can do it as well :slightly_frowning_face:

**Comment by dkocsis-emarsys** [comment]
Hello again!

I wanted to report this similar issue, when i saw that it's already here.
I'm not that experienced with typescript but I've just started to make a contribution on this issue, because it seems pretty easy to implement. And this is where i found another issue in insertBefore's implementation. Should i create another ticket on it?

The issue is with insertBefore's second parameter. According to the browser's behaviour and MDN, if this parameter is null, then the node should be appended after all children. I wrote a test on this specific case and it broke:

```
test('Inserts a Node after all children if no reference given.', () => {
	const child1 = document.createElement('span');
	const child2 = document.createElement('span');
	const newNode = document.createElement('span');
	const parent = document.createElement('div');

	parent.appendChild(child1);
	parent.appendChild(child2);
	parent.insertBefore(newNode, null);

	expect(newNode.parentNode).toBe(parent);
	expect(parent.childNodes[0]).toBe(child1);
	expect(parent.childNodes[1]).toBe(child2);
	expect(parent.childNodes[2]).toBe(newNode);
	expect(newNode.isConnected).toBe(false);

	document.body.appendChild(parent);

	expect(newNode.isConnected).toBe(true);
});
```

Also, i've noticed that .toEqual([...]) doesn't check the order of the given array items.

It's highly possible that i'm missing something here and there is a problem with my implementation and not with insertBefore's.

By the way, you have a nice name too!

Have a nice day!
David

**Comment by capricorn86** [comment]
Hi @dkocsis-emarsys! 

Yes, it seems like insertBefore() is missing this functionality.

Feel free to do all the fixes connected to this ticket if you want :slightly_smiling_face: 

Let me know if I can help out somehow!

**Comment by capricorn86** [comment]
@dkocsis-emarsys the test looks good!

**Comment by kr8n3r** [comment]
sorry folks I'm busy with other things and this wasn't a blocker, but ace to see movement 👏

**Comment by capricorn86** [comment]
No problem @kr8n3r! I have also been a little bit busy the last couple of weeks :sweat_smile: 

@dkocsis-emarsys saved the day and fixed it, so it is now available in the latest release:
https://github.com/capricorn86/happy-dom/releases/tag/v2.10.0
