### ISSUE TITLE
Require cycles warnung

### ISSUE THREAD

**Issue by myak2h** [capricorn86/happy-dom#229]
`WARN  Require cycle: node_modules/happy-dom/lib/nodes/document/Document.js -> node_modules/happy-dom/lib/dom-implementation/DOMImplementation.js -> node_modules/happy-dom/lib/nodes/document/Document.js`

**Comment by capricorn86** [comment]
Thanks for reporting @myak2h! :slightly_smiling_face: 

I will look into it as soon as possible. Most likely in a couple of days as I am quite busy right now.

**Comment by capricorn86** [comment]
The It is very easy to get circular dependencies in the DOM because of the nature of how it works.

In this case we have a dependency from Document to DOMImplementation as document uses it for the property document.implementation. DOMImplementation has a dependency to the Document as it needs the current document in the DOMImplementation.createDocumentType() method. It also needs the Document class to be able to create new instances of the document in DOMImplementation.createHTMLDocument() and DOMImplementation.createDocument().

Which tool are you building with @myak2h?

I have now fixed the issue. Hopefully you won't end up with more circular dependencies :sweat_smile: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.11.2
