### ISSUE TITLE
CharacterData is not defined

### ISSUE THREAD

**Issue by Ayc0** [capricorn86/happy-dom#329]
When importing the polyfill `element-remove`, I have this error

```
CharacterData is not defined
```

**Comment by Ayc0** [comment]
I opened this issue with 2 others #328 and 330 but I don't think I can implement this one (not sure how to proceed with this).

Though, I looked at the code and maybe we should make a global `CharacterData` that would implement `CharacterDataUtility`.

**Comment by capricorn86** [comment]
@Ayc0 I am working on a fix for it now :slightly_smiling_face: 

We need to change so that ICharacterData only implements the INode interface according to Mozilla docs.

Then there should be a base class called CharacterData that implements ICharacterData.

Then Comment and Text should extend from the CharacterData class.

**Comment by capricorn86** [comment]
Hi @Ayc0! :slightly_smiling_face: 

I have added support for Window.CharacterData now.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v2.28.0

**Comment by Ayc0** [comment]
Thanks @capricorn86 !!
