### ISSUE TITLE
document don't have baseURI 

### ISSUE THREAD

**Issue by green-mike** [capricorn86/happy-dom#485]
When 
```js
baseURI = document.baseURI
```
then
```js
 Cannot read properties of null (reading 'querySelector')
```

because ownerDocument is null 
```ts
	public get baseURI(): string {
		const base = <IHTMLBaseElement>this.ownerDocument.querySelector('base');
		if (base) {
			return base.href;
		}
		return this.ownerDocument.location.href;
	}
```

I'm not sure where to add Node.test when 'document' condition.

Open this issue because library 'mswjs' 
```ts  
  // https://github.com/mswjs/msw/blob/2e7ecd87e5568c6e59a408e812535f088498e437/src/utils/url/getAbsoluteUrl.ts
  
  // Resolve a relative request URL against a given custom "baseUrl"
  // or the document baseURI (in the case of browser/browser-like environments).
  const origin =
    baseUrl || (typeof document !== 'undefined' && document.baseURI)
```

Apologize for my English. thanks a lot.

**Comment by capricorn86** [comment]
Thanks for reporting @green-mike! :slightly_smiling_face: 

If would like to contribute, you probably need to do something like this:

1. Look at the [contribution instructions](https://github.com/capricorn86/happy-dom/blob/master/docs/contributing.md) for how to contribute
2. Copy `get baseURI()` from INode.ts and Node.ts to IDocument.ts and Document.ts
3. Copy unit tests for baseURI() from Node.test.ts to Document.test.ts

Otherwise I will fix this as soon as possible.

**Comment by capricorn86** [comment]
Now when I looked at the issue again, I realized that I probably misunderstood it. I am not sure why `this.ownerDocument` is null in this scenario. It should not be possible as the Element has been created.

**Comment by capricorn86** [comment]
In order to fix the issue we probably need to override `get baseURI()` in Document.ts and replace the logic from `this.ownerDocument` to `this`.

**Comment by capricorn86** [comment]
I will try to fix it as soon as possible.

**Comment by capricorn86** [comment]
@green-mike it should not be fixed :slightly_smiling_face: 

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v4.0.2

**Comment by green-mike** [comment]
I can use 'document.baseURI' without exception. thank you.
your test is clear so I can know to feature. good 👍
