### ISSUE TITLE
Missing `element.click()`

### ISSUE THREAD

**Issue by ekwoka** [capricorn86/happy-dom#645]
`IElement` returned by `document.querySelector` has a `click()` method that functions, but TypeScript says it does not exist.

Expected behavior: TypeScript not complain about this existing.

**Comment by capricorn86** [comment]
According to spec `Element.querySelector()` and `Document.querySelector()` should return elements of type `Element` which does not have the `click()` method. However, elements of type `HTMLElement` should have the `click()` method.

See HTMLElement interface:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click

See `Element.querySelector()`:
https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector

In order to solve this you just need to cast:
```javascript
const element = <HTMLElement>document.querySelector('div');
```
