### ISSUE TITLE
Implementing Adjacent Sibling Selectors

### ISSUE THREAD

**Issue by btea** [capricorn86/happy-dom#792]
**Is your feature request related to a problem? Please describe.**

The adjacent sibling combinator selector is not implemented.

**Comment by capricorn86** [comment]
Hi @btea! :slightly_smiling_face: 

This has been fixed in another PR as I wanted to do some refactor of the entire query selection logic in order to not hurt performance when implementing document order and adjacent sibling selectors.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.0
