### ISSUE TITLE
onChange is not triggered using userEvent.type

### ISSUE THREAD

**Issue by nilscox** [capricorn86/happy-dom#856]
**Describe the bug**

Using the `type` method of `@testing-library/user-event` does not trigger the `onChange` callback of an input. This happens with happy-dom@9.3.2.

**To Reproduce**

Here is a codesandbox reproducing the issue: https://codesandbox.io/p/sandbox/eloquent-carson-omsw2l?&file=%2Fsrc%2Frepro.spec.jsx

Running the `test` script starts jest with happy-dom, and results in an error. Running the `test:jsdom` script runs the same test with jsdom, but it does not fail.

**Expected behavior**

The input's `onChange` callback should be called.

**Additional context**

It may be related to #531.

**Comment by mperazac** [comment]
We have been experiencing the same issue. It used to work. Tracking down which version works well, in our case, starting from v8.2.4 userEvent.type no longer triggers the `onChange`.
Version 8.2.3 seems to work fine.

I wonder if this commit is the culprit: https://github.com/capricorn86/happy-dom/commit/cdd1b996fe040791c70ce212c1917efae0c75ad8

**Comment by capricorn86** [comment]
> 

@mperazac I checked out the code for 8.2.3, but I can't find that the "change" event is dispatched. Perhaps there is some logic in testing library that doesn't work after the change.

**Comment by capricorn86** [comment]
Hi @nilscox and @mperazac! :slightly_smiling_face: 

I believe the problem was introduced in this release:
https://github.com/capricorn86/happy-dom/releases/tag/v8.7.2

The reason for why it caused the problem is that Test Library is using the "capture" option to capture "focus" and "blur" events, as they are not bubbling according to spec. As the "focus" and "blur" event was bubbling before, it still worked in Happy DOM, but when it got corrected it stopped working as Happy DOM didn't have support for "capture".

I have now implemented support for "capture" and the problem should now be fixed.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.7.0

**Comment by nilscox** [comment]
Thanks @capricorn86 for your reactivity! I confirm that it is now working as expected.
Keep up the good work!  :100:
