### ISSUE TITLE
Allow setting the base URL

### ISSUE THREAD

**Issue by akaltar** [capricorn86/happy-dom#868]
**Is your feature request related to a problem? Please describe.**
When trying to migrate from `jest-environment-jsdom` I'm experiencing lots of issues around `about:blank` being the base URL because I'm trying to construct relative URLs

**Describe the solution you'd like**
Allow configuring the base URL in the base package + maybe change default for jest environment to match [jsdom](https://github.com/facebook/jest/blob/15af9b3b6f53a4f2f2e39d328eb6ef9f46ba91c4/packages/jest-environment-jsdom/src/index.ts#L65)

**Describe alternatives you've considered**
I'm just trying happy-dom out, but I'm not sure how could I override this without a feature in my test setup. Adding the base URL everywhere in this big project feels a bit too difficult

**Additional context**
Very closely related to discussion in #678

**Comment by kalvenschraut** [comment]
@capricorn86  I was able to see the base URL via `location.assign('https://localhost')` which I do in a "setup" file that is ran by vitest before each test suite file. Not sure if that is good enough for you @akaltar? Otherwise are you looking for happy-dom to read from some kind of configuration? 

https://vitest.dev/config/#environment, I only know about vitest as my runner but looks like vitest could maybe have the environmentOptions, I assume whatever runner would have similar abilities.

**Comment by akaltar** [comment]
This does seem to work for me, thank you @kalvenschraut!
I'll keep this discussion open in case it might help with easier migration from jsdom, if a default value will be considered in the future

**Comment by X-Y** [comment]
I encountered the same problem when trying to setup happy-dom with MSW. I'd vote for using http://localhost as default, to be consistent with js-dom.

**Comment by capricorn86** [comment]
@X-Y I believe that JSDom also defaults to "about:blank", but the test framework probably sets it to "http://localhost" in that case.

JSDom source code:
https://github.com/jsdom/jsdom/blob/master/lib/api.js#L204

**Comment by silvenon** [comment]
The reason why MSW throws is because it's using `location.origin`, if it finds one, for mocking endpoints, and the default `location.origin` in `happy-dom` is `null`, which is an invalid second parameter for the `new URL()` constructor, which is what MSW uses.

If the default `location.origin` was `undefined` that would have been fine. So I'm not sure what should be done about this, whether it's a MSW issue or a `happy-dom` issue.

**Comment by capricorn86** [comment]
@silvenon `location.origin` is set to "null" (as a string) in Chrome and FF in a page with "about:blank" as URL.

The simplest solution would probably be if Vitest sets the URL to "https://localhost" or similar. It doesn't feel right to me if Happy DOM sets a default URL.

**Comment by capricorn86** [comment]
I'm closing this as it has now been fixed in [v0.34.2](https://github.com/vitest-dev/vitest/releases/tag/v0.34.2) version of Vitest.

Vitest pull request:
https://github.com/vitest-dev/vitest/pull/3972

**Comment by capricorn86** [comment]
Sorry, I closed this a bit too quick. The issue is about Jest and not Vitest.

**Comment by capricorn86** [comment]
@akaltar sorry for misunderstanding the original issue. There is now a fix for `@happy-dom/jest-environment` which sets the default URL to "http://localhost".

https://github.com/capricorn86/happy-dom/releases/tag/v10.10.2

**Comment by evanre** [comment]
If anyone ever struggles with TanStack Router + Vitest + Happy DOM and encounters an “Invalid URL” error after updating to Happy DOM v18+

Adding this to `vite.config` is not enough
```js
environmentOptions: {
  happyDOM: {
    url: 'http://localhost/',
 },
},
```
You also need to add `origin` prop to your `createRouter`: 
```js
createRouter({
  ...,
  origin: 'http://localhost/',
})
````
I spent over 6 hours trying to solve this issue…
